### ISSUE TITLE
yarn dev環境で、Buyボタンを押すと「Wrong network detected」が発生する。

### ISSUE THREAD

**Issue by mogiken** [taijusanagi/chocomint#30]
yarn dev環境で、Buyボタンを押すと「Wrong network detected」が発生します。Metamaskは問題なくlocalhostのネットワークを選択しています。
signerNetwork.chainIdの値は1337、chainIdは31337になっており、なぜか先頭に3がついています。
```
    if (signerNetwork.chainId != chainId) {
      openModal("😲", `Wrong network detected, please connect to ${networkName}.`);
      return;
    } else {
      return signer;
    }
```

**Comment by mogiken** [comment]
根本原因は不明ですが、とりいそぎ、 contracts/network.jsのchainIdを変更して対応しました。

**Comment by taijusanagi** [comment]
ありがとうございます！
すみません、ドキュメントがちょっと揃ってなくて申し訳ないのですが、今回は開発環境にhardhat nodeを使っており、私が開発している時にはmetamaskのデフォルトのlocalhostだと、hardhatに繋がらないというmetamaskとhardhat部分の連携に不具合があり、そのためhainID31337のlocalhost:8545を別途metamaskに登録して開発を行っていました。不具合の内容は下記の通りです。

https://github.com/MetaMask/metamask-extension/issues/9827

ちなみに、chainIdを1337に直すとトランザクションの発行はできましたか？

**Comment by mogiken** [comment]
> ありがとうございます！
> すみません、ドキュメントがちょっと揃ってなくて申し訳ないのですが、今回は開発環境にhardhat nodeを使っており、私が開発している時にはmetamaskのデフォルトのlocalhostだと、hardhatに繋がらないというmetamaskとhardhat部分の連携に不具合があり、そのためhainID31337のlocalhost:8545を別途metamaskに登録して開発を行っていました。不具合の内容は下記の通りです。
> 
> [MetaMask/metamask-extension#9827](https://github.com/MetaMask/metamask-extension/issues/9827)
> 
> ちなみに、chainIdを1337に直すとトランザクションの発行はできましたか？

ご確認ありがとうございます。
1337ではうまくいかないので、metamaskにchainID31337のlocalhost:8545を追加して対応しました。これで動作に問題はなさそうです。
